[project]
name = "validacijas"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "duckdb==1.3.2",
    "python-dotenv>=1.1.1",
    "typer>=0.16.0",
]

[tool.ruff.format]
quote-style = "single"
